name: Workflow 1
on: workflow_dispatch
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Download Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Lint Code
              run: npm run lint
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Download Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm test
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Deploy changes
              run: npm run build