name: Workflow 1
on: workflow_dispatch
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Download Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Lint Code
              run: npm run test
    Build:
        needs: Lint
        runs-on: ubuntu-latest
        outputs:
            script-file: ${{ steps.publish.outputs.script-file }}
        steps:
            - name: Download Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Publish files to Output
              id : publish
              run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
            - name: Install dependencies
              run: npm run build
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist-artifact
                path: dist
    Deploy:
        needs: Build
        runs-on: ubuntu-latest
        steps:
            - name: Downloading artifacts
              uses: actions/download-artifact@v4
              with:
                name: dist-artifact
            - name: Output Artifacts
              run: ls
            - name: Output filename
              run: echo "${{ needs.Build.outputs.script-file}}"
            - name: Deploy changes
              run: echo "Deploying..."