name: Reusable workflow
on: 
    workflow_call:
      inputs:
        artifact-name:
          description: The name of the deployable artifact files
          required: false
          default: dist
          type: string
      outputs:
        result:
          description: Print Output
          value: ${{ jobs.deploy.outputs.outcome }}
jobs:
    deploy:
        outputs:
            outcome: ${{ steps.set-result.outputs.set-result}}
        runs-on: ubuntu-latest
        steps:
          - name: Download artifacts
            uses: actions/download-artifact@v4
            with:
                name: ${{ inputs.artifact-name }}
          - name: Reusing the Deploy workflow
            run: echo "Deploying the code"
          - name: Set result output
            id: set-result
            run: echo "set-result=success" >> GITHUB_OUTPUT

